version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: theralink-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: theralink
    ports:
      - "3306:3306"
    volumes:
      - theralink-db-data:/var/lib/mysql

  backend:
    build: .
    container_name: theralink-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/theralink
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    ports:
      - "8586:8586"

  frontend:
    build:
      context: D:\workspace\angular\theraLinkUI
    container_name: theralink-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  theralink-db-data:
