spring:
  datasource:
    username: root
    password: ALmhxmVFYpvlzLlfuhMp
    url: jdbc:mysql://theralink-db.theralink.svc/mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



