spring:
  datasource:
    username: root
    password: Mehr@zin123
    url: jdbc:mysql://185.79.157.44:3306/mehr
#    url: jdbc:mysql://localhost:3306/mehr
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect





