spring:
  datasource:
    username: root
    password: ALmhxmVFYpvlzLlfuhMp
    url: jdbc:mysql://theralink-db.theralink.svc/mysql?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


